### ISSUE TITLE
Already loaded in CWX?

### ISSUE THREAD

**Issue by ghost** [nosoop/SM-TFCW3toX#1]
I've added the plugin to my server, however I encountered this:

L 12/27/2021 - 15:29:50: [SM] Exception reported: Failed to create native "CW3_AddAttribute", name is probably already in use
L 12/27/2021 - 15:29:50: [SM] Blaming: cw3toX.smx
L 12/27/2021 - 15:29:50: [SM] Call stack trace:
L 12/27/2021 - 15:29:50: [SM]   [0] CreateNative
L 12/27/2021 - 15:29:50: [SM]   [1] Line 36, scripting/cw3toX.sp::AskPluginLoad2
L 12/27/2021 - 15:29:50: [SM] Failed to load plugin "cw3toX.smx": unexpected error 23 in AskPluginLoad callback.
L 12/27/2021 - 15:47:45: Error log file session closed.

I assume that CWX itself already uses CW3_AddAttribute without CW3toX?

I gotta mention I have the cw3_attributes.smx module installed from CW3.

**Comment by nosoop** [comment]
Per the project README, the `cw3_attributes` plugin can't be running - this is the exact reason why.

**Comment by ghost** [comment]
> Per the project README, the `cw3_attributes` plugin can't be running - this is the exact reason why.

Ah, my bad. It was a bit confusing, but I get it now.
